use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

const OAUTH_EMBED_KEYS: &[&str] = &[
    "RUSTYMAIL_GOOGLE_OAUTH_CLIENT_ID",
    "RUSTYMAIL_GOOGLE_OAUTH_CLIENT_SECRET",
    "RUSTYMAIL_MICROSOFT_OAUTH_CLIENT_ID",
    "RUSTYMAIL_OAUTH_LOOPBACK_PORT",
];

fn normalize_dotenv_value(raw: &str) -> String {
    let t = raw.trim();
    if (t.starts_with('"') && t.ends_with('"') && t.len() >= 2)
        || (t.starts_with('\'') && t.ends_with('\'') && t.len() >= 2)
    {
        t[1..t.len() - 1].trim().to_string()
    } else {
        t.to_string()
    }
}

fn escape_rust_string(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
}

fn parse_dotenv_oauth(path: &Path) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    let Ok(content) = std::fs::read_to_string(path) else {
        return out;
    };
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim();
        if !OAUTH_EMBED_KEYS.contains(&key) {
            continue;
        }
        let value = normalize_dotenv_value(value);
        if !value.is_empty() {
            out.insert(key.to_string(), value);
        }
    }
    out
}

fn collect_oauth_embed_vars(repo_root: &Path) -> BTreeMap<String, String> {
    let mut vars = BTreeMap::new();

    // 1) Process env (CI / shell) wins for each key present.
    for key in OAUTH_EMBED_KEYS {
        if let Ok(raw) = std::env::var(key) {
            let value = normalize_dotenv_value(&raw);
            if !value.is_empty() {
                vars.insert((*key).to_string(), value);
            }
        }
    }

    // 2) Fill gaps from repo-root `.env` (local release / personal builds).
    let env_path = repo_root.join(".env");
    println!("cargo:rerun-if-changed={}", env_path.display());
    for (key, value) in parse_dotenv_oauth(&env_path) {
        vars.entry(key).or_insert(value);
    }

    for key in OAUTH_EMBED_KEYS {
        println!("cargo:rerun-if-env-changed={key}");
    }

    vars
}

/// Génère `OUT_DIR/oauth_embed.rs` : client OAuth publics embarqués pour que le binaire
/// release puisse faire PKCE + loopback sans `.env` ni serveur RustyMail.
fn write_oauth_embed_rs(vars: &BTreeMap<String, String>) {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let dest = PathBuf::from(&out_dir).join("oauth_embed.rs");
    let mut code = String::from(
        "// @generated by build.rs — do not edit\n\
         // Public-client OAuth credentials for desktop PKCE (no RustyMail backend).\n\
         // Google Desktop `client_secret` is non-confidential per Google installed-app docs.\n\n",
    );
    code.push_str("pub(crate) fn inject_embedded_oauth_env() {\n");
    if vars.is_empty() {
        code.push_str(
            "    // No OAuth client credentials at build time — buttons stay disabled unless\n\
             // RUSTYMAIL_* is set at runtime (dev) or the next build embeds them.\n",
        );
    } else {
        for (key, value) in vars {
            let escaped = escape_rust_string(value);
            code.push_str("    if std::env::var(\"");
            code.push_str(key);
            code.push_str("\").ok().filter(|s| !s.trim().is_empty()).is_none() {\n");
            code.push_str("        std::env::set_var(\"");
            code.push_str(key);
            code.push_str("\", \"");
            code.push_str(&escaped);
            code.push_str("\");\n");
            code.push_str("    }\n");
        }
    }
    code.push_str("}\n");

    std::fs::write(&dest, code).unwrap_or_else(|e| {
        panic!("écriture de {} impossible: {e}", dest.display())
    });
}

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let repo_root = manifest_dir.join("..");
    let vars = collect_oauth_embed_vars(&repo_root);
    write_oauth_embed_rs(&vars);
    tauri_build::build();
}
