use std::path::{Path, PathBuf};

fn normalize_dotenv_value(raw: &str) -> String {
    let t = raw.trim();
    if (t.starts_with('"') && t.ends_with('"') && t.len() >= 2)
        || (t.starts_with('\'') && t.ends_with('\'') && t.len() >= 2)
    {
        t[1..t.len() - 1].trim().to_string()
    } else {
        t.to_string()
    }
}

fn escape_rust_string(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
}

/// Génère `OUT_DIR/oauth_embed.rs` : injection des clés OAuth au démarrage (release perso).
fn embed_oauth_from_dotenv(repo_root: &Path) {
    let env_path = repo_root.join(".env");
    if !env_path.is_file() {
        panic!(
            "feature embed-dev-oauth: fichier `.env` introuvable à {}",
            env_path.display()
        );
    }

    let content = std::fs::read_to_string(&env_path).unwrap_or_else(|e| {
        panic!(
            "feature embed-dev-oauth: lecture de {} impossible: {e}",
            env_path.display()
        )
    });

    let mut vars = Vec::new();
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let Some((key, value)) = line.split_once('=') else {
            continue;
        };
        let key = key.trim();
        let value = normalize_dotenv_value(value);
        if key.starts_with("RUSTYMAIL_") && !value.is_empty() {
            vars.push((key.to_string(), value));
        }
    }

    if vars.is_empty() {
        panic!(
            "feature embed-dev-oauth: aucune variable RUSTYMAIL_* non vide dans {}",
            env_path.display()
        );
    }

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let dest = PathBuf::from(&out_dir).join("oauth_embed.rs");
    let mut code = String::from("// @generated by build.rs — do not edit\n\n");
    code.push_str("pub(crate) fn inject_embedded_oauth_env() {\n");
    for (key, value) in &vars {
        let escaped = escape_rust_string(value);
        code.push_str(&format!(
            "    if std::env::var(\"{key}\").is_err() {{ std::env::set_var(\"{key}\", \"{escaped}\"); }}\n"
        ));
    }
    code.push_str("}\n");

    std::fs::write(&dest, code).unwrap_or_else(|e| {
        panic!(
            "feature embed-dev-oauth: écriture de {} impossible: {e}",
            dest.display()
        )
    });
    println!("cargo:rerun-if-changed={}", env_path.display());
}

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    if std::env::var("CARGO_FEATURE_EMBED_DEV_OAUTH").is_ok() {
        embed_oauth_from_dotenv(&manifest_dir.join(".."));
    }
    tauri_build::build();
}
