import { defaultAppPrefs } from "../prefs_defaults";
import { defaultOrganizationState } from "../organizationView";
import { defaultOrganizationV2State } from "../organizationViewV2";
import { defaultFolderManagerState } from "../folderManagerView";
import type { State } from "./types";

const SIDEBAR_COLLAPSED_STORAGE_KEY = "rustymail.sidebarCollapsed";

function readSidebarCollapsedPreference(): boolean {
  try {
    return window.localStorage.getItem(SIDEBAR_COLLAPSED_STORAGE_KEY) === "1";
  } catch {
    return false;
  }
}

export const state: State = {
  view: "list",
  accounts: [],
  selectedAccountId: undefined,
  settingsSelectedAccountId: "new",
  settingsTab: "accounts",
  newsletterRules: [],
  appPrefs: defaultAppPrefs(),
  dictationApiKeySet: false,
  openrouterApiKeySet: false,
  llamaServerApiKeySet: false,
  oauthGoogleConfigured: false,
  oauthMicrosoftConfigured: false,
  accountMessage: "",
  accountsLoadError: "",
  mailListError: "",
  syncMessage: "",
  syncInProgress: false,
  syncProgressBatch: null,
  statusBarJobs: [],
  lastAppPaths: null,
  settingsPathsLoadError: "",
  composeMessage: "",
  selectedMailbox: "INBOX",
  mailboxes: [],
  mailboxUnread: {},
  inboxFilterCounts: null,
  mailboxTotal: {},
  threads: [],
  threadOffset: 0,
  threadPageSize: 50,
  hasMoreThreads: false,
  remoteImagesAllowedByMessage: {},
  addressBookSidebarCount: null,
  organization: defaultOrganizationState(),
  organizationV2: defaultOrganizationV2State(),
  folderManager: defaultFolderManagerState(),
  savedSearches: [],
  suggestedSavedViews: [],
  activeSavedSearchId: null,
  savedSearchMarkingSeenId: null,
  searchViewBatchJob: null,
  search: "",
  searchDraft: "",
  searchSenders: [],
  searchMailboxPath: null,
  searchAccountOverrideId: null,
  searchTags: [],
  searchTagCatalog: [],
  searchNewsletterRule: null,
  searchScope: "account",
  searchModifiersTouched: false,
  searchNlMode: null,
  searchLanguageFilter: null,
  searchRelativeDays: null,
  searchHasAttachment: null,
  searchMinSecurityScore: null,
  searchMailboxPrefix: null,
  searchModalOpen: false,
  settingsAiModal: null,
  aiEngineSettingsTab: "local",
  promptCatalog: null,
  promptCatalogLoadError: "",
  llmJobLabel: null,
  semanticModelAvailable: false,
  semanticEmbeddingCounts: null,
  llmRuntimeStatus: null,
  llmCachedGgufFilenames: [],
  llmPrefetchPercent: null,
  llmPrefetchInFlight: false,
  idleAiCachePrefetchBusy: false,
  aiOpen: false,
  aiQuickPanelOpen: false,
  aiOutput: "",
  previewOpen: true,
  composeLayout: "split",
  composeBody: "",
  composeCanonicalBody: "",
  draftSessionId: null,
  savedDraftRecordId: null,
  draftRevisionsLoading: false,
  draftRevisions: [],
  draftDiffRevisionId: null,
  draftDiffLoading: false,
  draftDiffLines: [],
  draftDiffView: "preview",
  draftDiffOtherBody: "",
  draftRevisionPreview: null,
  draftVersionsListExpanded: false,
  micState: "idle",
  micSeconds: 0,
  tone: "Professional",
  moveOpen: false,
  moveThreadId: undefined,
  moveTargetMailbox: "INBOX",
  mailboxManageOpen: false,
  /** `clean` = lisible quand le nettoyage apporte un contenu distinct, sinon brut par message ; `original` = tout en brut. */
  messageViewMode: "clean",
  personalFoldersOpen: false,
  composeAdvancedOpen: false,
  composeCcBccOpen: false,
  listFilter: "all",
  mailboxBriefBannerHtml: "",
  mailboxDigestKey: "",
  mailboxDigestLive: false,
  mailboxDigestPanelOpen: false,
  mailboxDigestRefreshing: false,
  mailboxActionBrief: null,
  mailboxBriefMode: "auto",
  aiThreadScope: null,
  messageTranslations: {},
  messageTranslationBusy: {},
  quickReplySuggestions: [],
  agentSession: null,
  threadQaDraft: "",
  threadQaAnswer: null,
  threadQaStreamText: "",
  composeGrammarSuggestions: null,
  quoteFoldModal: null,
  threadQuickReplyOpen: false,
  threadTagsModalOpen: false,
  imageModal: null,
  splitSendConfirm: null,
  sidebarCollapsed: readSidebarCollapsedPreference(),
  savedDraftsMailboxCount: 0,
  personalTreeOpen: {},
  closeComposeModal: null,
  resumeDraftModal: null,
  accountServersPanelOpen: false,
  oauthLockedEmail: null,
  accountFormAuthKind: "password",
  accountFormOAuthPrefill: null,
  accountPasswordSetupExpanded: false,
  accountOAuthWizardPhase: null,
  accountOAuthWizardMessage: "",
  accountOAuthWizardError: null,
  accountOAuthWizardRetry: null,
};
